"""Build the local render contact sheet from the coordinated model report."""
import html
import json
from pathlib import Path
R=Path(__file__).resolve().parents[2];O=R/'output/blender/coastal-house'
report=json.loads((O/'model-report.json').read_text())
labels={'arrival':'Arrival and linked garage','garden':'Garden elevation and sheltered terrace','coastal-plot':'The coastal plot','ground-cutaway':'Ground floor','first-cutaway':'First floor and office wing','parents-bedroom':'Parents bedroom','suite-gallery':'Landing to suite gallery','dressing':'Dressing room','bathroom':'Parents bathroom','bathroom-vanity':'Double vanity and bathroom detail','family-bedroom':'Family bedroom','library':'Library and snug','gym':'Gym','office':'Office and guest space','combined-room':'Approved kitchen, dining and living','terrace':'Outdoor dining terrace'}
cards=''.join(f'<figure id="{n}"><a href="../output/blender/coastal-house/{n}.png"><img loading="lazy" src="../output/blender/coastal-house/{n}.png" alt="{html.escape(labels[n])}"></a><figcaption>{labels[n]}</figcaption></figure>' for n in report['views'])
(R/'viewer-coastal/gallery.html').write_text('''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Coastal house — rendered views</title><style>*{box-sizing:border-box}body{margin:0;background:#f2f0e8;color:#27362e;font:16px/1.6 system-ui,sans-serif}main{max-width:1500px;margin:auto;padding:40px 28px}h1{font:400 clamp(32px,5vw,62px)/1.1 Georgia,serif;margin:12px 0}p{max-width:850px}a{color:#345e4e}nav{display:flex;gap:22px;flex-wrap:wrap;margin:24px 0}section{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:28px}figure{margin:0}figure:first-child,figure:nth-child(3){grid-column:1/-1}img{width:100%;display:block;background:#d3d9d0;border-radius:3px}figcaption{padding:8px 0 14px}small{color:#57635a}.note{border-top:1px solid #b7bfb2;padding-top:22px;margin-top:28px}@media(max-width:760px){main{padding:24px 16px}section{display:block}figure{margin-bottom:22px}}</style><main><small>L01.1 · COORDINATED DESIGN STUDY · 8 OCTOBER 2026</small><h1>A house by the coast</h1><p>The revised two-storey L-house, with the approved kitchen and living room, a private parents suite, family rooms, linked garage and office, and a sheltered coastal garden.</p><nav><a href="index.html">Open interactive model</a><a href="#first-cutaway">First floor</a><a href="#parents-bedroom">Parents suite</a><a href="#coastal-plot">Plot</a></nav><section>'''+cards+'''</section><div class="note"><p><strong>Design basis.</strong> Measured plan L01.1 and the selected Option D pantry. Proposed house section: 3.20 m ceiling datum and 3.50 m first-floor datum. With the retained 40 mm floor finish, clear heights are 3.16 m downstairs and 2.66 m upstairs. The garage retains its 3.00 m floor-to-floor height. Four suite rooflights have roof openings and light wells.</p><p>The 40 × 65 m plot, coast, planting and daylight are illustrative. The burner is saved as a hidden option because its current flue conflicts with the suite gallery. Structural design, services, products and occupied use remain to be resolved.</p><p><a href="../output/blender/coastal-house/geometry-checks.json">Geometry check results</a> · <a href="../output/blender/coastal-house/model-report.json">Model and source record</a></p></div></main></html>''')
print(R/'viewer-coastal/gallery.html')
