const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'../..'),out=path.join(root,'tmp/coastal-browser');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],requests=[];page.on('pageerror',e=>{errors.push(String(e));console.error('PAGE_ERROR',String(e));});page.on('console',m=>{if(m.type()==='error')console.error('CONSOLE',m.text());});page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:4197/')&&!r.url().startsWith('data:')&&!r.url().startsWith('blob:'))requests.push(r.url());});
page.setDefaultTimeout(90000);
await page.goto('http://127.0.0.1:4197/viewer-coastal/');await page.waitForFunction(()=>window.coastalHouse,{},{timeout:180000});
const report=await page.evaluate(()=>{const h=window.coastalHouse;let meshes=0,triangles=0;h.model.traverse(o=>{if(o.isMesh){meshes++;triangles+=(o.geometry.index?.count||o.geometry.attributes.position.count)/3;}});return{meshes,triangles,views:Object.keys(h.report.views),groups:h.model.children.map(o=>({name:o.name,level:o.userData.level,part:o.userData.part}))};});
const showerDoorPoses=await page.evaluate(()=>{const h=window.coastalHouse;let door;h.model.traverse(o=>{if(o.userData.door_type==='shower')door=o;});if(!door)throw Error('Shower door missing');h.setView('bathroom-shower-closed');const closed=door.quaternion.toArray();h.setView('bathroom-shower');const open=door.quaternion.toArray();if(Math.abs(closed[3]-1)>1e-6||Math.abs(open[3]-Math.SQRT1_2)>1e-5)throw Error('Shower door pose incorrect');return{closed,open};});
const pantryDoorPoses=await page.evaluate(()=>{const h=window.coastalHouse;let door;h.model.traverse(o=>{if(o.userData.door_type==='pantry')door=o;});if(!door)throw Error('Concealed pantry door missing');h.setView('kitchen-storage');const closed=door.quaternion.toArray();h.setView('pantry');const open=door.quaternion.toArray();if(Math.abs(open[3]-1)>1e-6||Math.abs(closed[3]-Math.SQRT1_2)>1e-5)throw Error('Pantry door pose incorrect');return{closed,open};});
for(const view of report.views){await page.selectOption('#view',view);await page.waitForFunction(v=>window.coastalHouse.state.view===v,view);await page.screenshot({path:path.join(out,view+'.png')});}
for(const mode of ['ground','first','all']){await page.selectOption('#floor',mode);const visible=await page.evaluate(()=>coastalHouse.model.children.filter(o=>o.visible).map(o=>o.userData));if(mode!=='all'&&visible.some(o=>['roof','ceilings'].includes(o.part)))throw Error('Roof visible in cutaway');if(mode==='ground'&&visible.some(o=>['u','o'].includes(o.level)))throw Error('Upper floor visible in ground cutaway');}
await page.setViewportSize({width:390,height:844});await page.selectOption('#view','coastal-plot');await page.screenshot({path:path.join(out,'phone.png')});
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow)throw Error('Phone overflow');if(errors.length||requests.length)throw Error(JSON.stringify({errors,requests}));
fs.writeFileSync(path.join(root,'output/blender/coastal-house/browser-checks.json'),JSON.stringify({...report,showerDoorPoses,pantryDoorPoses,glbSha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'output/blender/coastal-house/coastal-house.glb'))).digest('hex'),errors,externalRequests:requests,phoneWidth:390,overflow},null,2));console.log(JSON.stringify({views:report.views.length,meshes:report.meshes,triangles:report.triangles,errors,externalRequests:requests,phoneOverflow:overflow}));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
