import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from '../viewer/vendor/GLTFLoader.js';
import {batchStatic} from '../viewer-l-house/batch_static.js';
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;document.getElementById('scene').append(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('#e3e7df');const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.04,400);const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.minDistance=.3;orbit.maxDistance=150;
const hemi=new THREE.HemisphereLight('#fff8e9','#78825e',2);scene.add(hemi);const sun=new THREE.DirectionalLight('#fff0d1',3);sun.position.set(-18,35,-28);sun.target.position.set(10,0,7);scene.add(sun,sun.target);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-32,right:32,top:32,bottom:-32,far:100});sun.shadow.normalBias=.03;
const canvas=document.createElement('canvas');canvas.width=512;canvas.height=256;const ctx=canvas.getContext('2d'),gradient=ctx.createLinearGradient(0,0,0,256);gradient.addColorStop(0,'#8eacbd');gradient.addColorStop(.5,'#e3e7dd');gradient.addColorStop(1,'#c1b38e');ctx.fillStyle=gradient;ctx.fillRect(0,0,512,256);const sky=new THREE.CanvasTexture(canvas);sky.mapping=THREE.EquirectangularReflectionMapping;sky.colorSpace=THREE.SRGBColorSpace;const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromEquirectangular(sky).texture;sky.dispose();pmrem.dispose();
let pending=false,model;
function render(){pending=false;orbit.update();renderer.render(scene,camera);}
function requestRender(){if(!pending){pending=true;requestAnimationFrame(render);}}
orbit.addEventListener('change',requestRender);
const views={arrival:{p:[-13,12,39],t:[12,2.8,10]},garden:{p:[14,7,-15],t:[9,3,6]},living:{p:[3.35,1.65,8.75],t:[3.3,1.3,1]},kitchen:{p:[10.25,1.65,8.85],t:[8.1,1.25,5.7]},parents:{p:[5.6,4.65,3.9],t:[2.8,4.2,1.3]},office:{p:[21.95,4.65,19.75],t:[24.2,4.15,15.8]},ground:{p:[24,33,28],t:[12,0,10]},first:{p:[24,34,28],t:[12,3,10]}};
function setFloor(mode){for(const id of ['g','a','u','o'])model.getObjectByName(id).visible=mode==='all'||(mode==='ground'?['g','a'].includes(id):['u','o'].includes(id));for(const id of ['Roofs','Ceilings'])model.getObjectByName(id).visible=mode==='all';document.getElementById('floor').value=mode;renderer.shadowMap.needsUpdate=true;requestRender();}
function setView(name){const view=views[name];camera.position.set(...view.p);orbit.target.set(...view.t);if(['arrival','garden','ground','first'].includes(name))camera.position.sub(orbit.target).multiplyScalar(Math.max(1,.95/camera.aspect)).add(orbit.target);setFloor(['ground','first'].includes(name)?name:'all');orbit.update();document.getElementById('view').value=name;requestRender();}
try{const gltf=await new GLTFLoader().loadAsync('../output/blender/l-house/l-house.glb');model=gltf.scene;scene.add(model);model.traverse(o=>{if(o.isMesh){o.castShadow=o.userData.cast_shadow!==false&&!o.material.transparent;o.receiveShadow=true;}});for(const name of ['g','a','u','o','Roofs','Ceilings','Stairs','Site']){const group=model.getObjectByName(name);if(group)batchStatic(group);}setView('arrival');document.getElementById('status').textContent='Blender export · Measured L01 geometry';window.blenderStudy={model,scene,camera,renderer,setView,setFloor,views};}catch(error){document.getElementById('status').textContent='The Blender export could not load.';throw error;}
document.getElementById('view').addEventListener('change',e=>setView(e.target.value));document.getElementById('floor').addEventListener('change',e=>setFloor(e.target.value));window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);requestRender();});
