import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from '../viewer/vendor/GLTFLoader.js';
import {HDRLoader} from '../viewer/vendor/HDRLoader.js';
import {batchStatic} from '../viewer-l-house/batch_static.js';
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.AgXToneMapping;renderer.toneMappingExposure=2**.4;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.shadowMap.autoUpdate=false;document.getElementById('scene').append(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('#e3e7df');const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.04,400);const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.minDistance=.3;orbit.maxDistance=150;
const hemi=new THREE.HemisphereLight('#dbe5ed','#716349',.08);scene.add(hemi);const sun=new THREE.DirectionalLight(new THREE.Color(1,.88,.72),2.5);sun.position.set(-18,35,-28);sun.target.position.set(10,0,7);scene.add(sun,sun.target);sun.castShadow=true;sun.shadow.mapSize.set(4096,4096);Object.assign(sun.shadow.camera,{left:-32,right:32,top:32,bottom:-32,far:100});sun.shadow.normalBias=.012;sun.shadow.bias=-.0001;sun.shadow.radius=8;
const sky=await new HDRLoader().loadAsync('../output/blender/l-house/daylight.hdr');sky.mapping=THREE.EquirectangularReflectionMapping;const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromEquirectangular(sky).texture;scene.background=sky;pmrem.dispose();
const roomLights=[];for(const [x,y,z,power]of [[3.5,2.35,3,32],[3.5,2.35,6.6,24],[8.8,2.35,7.3,28],[3.4,5.35,2.3,24],[23,5.35,17,32]]){const light=new THREE.PointLight(new THREE.Color(1,.84,.62),power,8,2);light.position.set(x,y,z);light.castShadow=true;light.shadow.mapSize.set(512,512);light.shadow.radius=4;light.shadow.camera.near=.1;light.shadow.normalBias=.015;light.shadow.bias=-.0002;scene.add(light);roomLights.push(light);}
let pending=false,model;
function render(){pending=false;orbit.update();renderer.render(scene,camera);}
function requestRender(){if(!pending){pending=true;requestAnimationFrame(render);}}
orbit.addEventListener('change',requestRender);
const views={arrival:{p:[-13,12,39],t:[12,2.8,10]},garden:{p:[14,7,-15],t:[9,3,6]},living:{p:[3.35,1.65,8.75],t:[3.3,1.3,1]},kitchen:{p:[10.25,1.65,8.85],t:[8.1,1.25,5.7]},parents:{p:[5.6,4.65,3.9],t:[2.8,4.2,1.3]},office:{p:[21.95,4.65,19.75],t:[24.2,4.15,15.8]},ground:{p:[24,33,28],t:[12,0,10]},first:{p:[24,34,28],t:[12,3,10]}};
function setFloor(mode){for(const id of ['g','a','u','o'])model.getObjectByName(id).visible=mode==='all'||(mode==='ground'?['g','a'].includes(id):['u','o'].includes(id));for(const id of ['Roofs','Ceilings'])model.getObjectByName(id).visible=mode==='all';for(const light of roomLights)light.visible=mode==='all';document.getElementById('floor').value=mode;renderer.shadowMap.needsUpdate=true;requestRender();}
function setView(name){const view=views[name],interior=['living','kitchen','parents','office'].includes(name);scene.environmentIntensity=interior?.3:1;hemi.color.set(interior?'#fff0d4':'#dbe5ed');hemi.groundColor.set(interior?'#b88645':'#716349');hemi.intensity=interior?.65:.08;camera.fov=2*THREE.MathUtils.radToDeg(Math.atan(24/(2*({arrival:30,garden:28,living:22,kitchen:22,parents:24,office:23}[name]||30))));camera.updateProjectionMatrix();renderer.toneMappingExposure=2**(interior?.3:.4);camera.position.set(...view.p);orbit.target.set(...view.t);if(['arrival','garden','ground','first'].includes(name))camera.position.sub(orbit.target).multiplyScalar(Math.max(1,1.5/camera.aspect)).add(orbit.target);setFloor(['ground','first'].includes(name)?name:'all');orbit.update();document.getElementById('view').value=name;requestRender();}
try{const gltf=await new GLTFLoader().loadAsync('../output/blender/l-house/l-house.glb');model=gltf.scene;scene.add(model);model.traverse(o=>{if(o.isMesh){const glass=o.material.transmission>0;o.castShadow=o.userData.cast_shadow!==false&&!o.material.transparent&&!glass&&!['#f6e8c6','_f6e8c6'].includes(o.material.name);o.receiveShadow=!glass;}});for(const name of ['g','a','u','o','Roofs','Ceilings','Stairs','Site']){const group=model.getObjectByName(name);if(group)batchStatic(group);}setView('arrival');document.getElementById('status').textContent='Blender export · Measured L01 geometry';window.blenderStudy={model,scene,camera,renderer,setView,setFloor,views};}catch(error){document.getElementById('status').textContent='The Blender export could not load.';throw error;}
document.getElementById('view').addEventListener('change',e=>setView(e.target.value));document.getElementById('floor').addEventListener('change',e=>setFloor(e.target.value));window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);requestRender();});
