from pathlib import Path
import json,hashlib
R=Path(__file__).resolve().parents[2]
O=R/'output/design/kitchen-selections';O.mkdir(parents=True,exist_ok=True)
raw=(R/'studies/l-house-booklet/plans.json').read_bytes();plans=json.loads(raw)
model=json.loads((R/'viewer-l-house/model.json').read_text())
def area(p):return abs(sum(a[0]*b[1]-b[0]*a[1] for a,b in zip(p,p[1:]+p[:1])))/2
base={r['id']:r for r in plans['default']['rooms'] if r['floor']=='g'}
metrics={'living':area(base['G1']['p']),'kitchen':area(base['G2']['p']),'hall':area(base['G8']['p']),'pantry_utility':area(base['G3']['p']),'narrow_gain':5.85*.35,'open_hall_reassigned':5.85*1.55,'open_partition_recovered':5.85*.15}
data={'plans':{k:{a:plans[k][a] for a in ['rooms','furniture','doors','openings','house']} for k in ['default','enclosed']},'windows':[w for w in model['windows'] if w['floor']=='g'],'metrics':metrics,'source_sha256':hashlib.sha256(raw).hexdigest()}
(O/'zoning-source.json').write_text(json.dumps(data,indent=2))
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>L-house · Space and light study</title><style>
*{box-sizing:border-box}body{margin:0;background:#f3f0e8;color:#283b31;font:16px/1.55 system-ui,sans-serif}header,main,footer{max-width:1240px;margin:auto;padding:30px}header{padding-top:45px}h1{font:normal clamp(34px,5vw,54px)/1.12 Georgia,serif;margin:12px 0 22px}h2{font:normal 30px/1.2 Georgia,serif;margin:8px 0 18px}h3{font-size:18px;margin:12px 0}p{max-width:900px}a{color:inherit;text-underline-offset:3px}.eyebrow{font-size:12px;letter-spacing:2px;text-transform:uppercase;color:#647261}.summary{padding:22px 26px;background:#284836;color:#fff}.summary p{margin:6px 0}.note{font-size:13px;color:#61715f}.summary .note{color:#d4dfce}.controls{display:flex;flex-wrap:wrap;gap:16px;background:#e6e7dd;padding:18px;margin:20px 0}label{font-size:13px;display:grid;gap:5px;flex:1;min-width:165px}select{font:inherit;color:#253b2d;background:#fffdf7;border:1px solid #a6b29d;border-radius:3px;padding:10px;width:100%}.layout{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(270px,1fr);gap:28px}.panel{background:#fffdf7;border:1px solid #d3d5c7;padding:22px;min-width:0}svg{width:100%;height:auto;display:block}.metrics{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:18px}.metric{padding:12px;background:#e9ecdf}.metric b{display:block;font:normal 25px Georgia,serif}.metric span{font-size:12px}.legend{display:flex;flex-wrap:wrap;gap:12px;font-size:12px;margin:14px 0}.key{display:flex;align-items:center;gap:5px}.key i{display:inline-block;width:18px;height:5px}.sections{margin-top:38px;padding-top:28px;border-top:1px solid #c6cdbc}.twocol{display:grid;grid-template-columns:1fr 1fr;gap:24px}.image{width:100%;height:370px;object-fit:contain;background:#e8e5db}ul{padding-left:20px}li{margin:8px 0}.callout{padding:14px 18px;background:#f0e1c8;border-left:3px solid #9c713d}table{border-collapse:collapse;width:100%;font-size:14px}td,th{text-align:left;padding:10px 8px;border-bottom:1px solid #d3d5c7}th{font-size:12px}.overflow{overflow-x:auto}.dimension{font:14px system-ui}.route-label{font:15px system-ui;paint-order:stroke;stroke:#fffdf7;stroke-width:4px}footer{font-size:13px;color:#5f6b59}button{padding:8px 14px;font:inherit;background:#284836;color:white;border:0;border-radius:3px;cursor:pointer}.caption{font-size:13px;margin-top:8px}.columns{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}@media(max-width:820px){.layout,.twocol,.columns{grid-template-columns:1fr}header,main,footer{padding:20px}.panel{padding:16px}.controls{gap:10px}h2{font-size:26px}.image{height:310px}}@media print{.controls{display:none}.layout{grid-template-columns:1.4fr 1fr}header,main,footer{padding:12px}.sections{break-before:page}body{background:white}.panel{break-inside:avoid}}
</style></head><body><header><div class="eyebrow">L-house / Study 03 / 7 October 2026</div><h1>More room.<br>Light between spaces.</h1><p>Compare the hall, pantry and dividers before changing the house model. The plan uses the measured L-house booklet geometry, with the later living-room changes noted separately.</p><div class="summary"><p><strong>Kitchen choices confirmed:</strong> 1B country cabinet profile · 2A quiet pale surface · 4B milk-glass pendants · Belfast-style sink.</p><p><strong>Island:</strong> dark oak, framed panels, substantial corner posts and a shaped countertop edge.</p><p class="note">Stools await your new reference. Tap remains open: test a single-lever mixer with a pull-out rinse. The surface colour is selected; the material and construction of the shaped edge still need checking.</p></div><p><a href="index.html">Kitchen reference sheet ↗</a> · <a href="boot-room.html"><strong>New: option D — reclaim boot-room space ↗</strong></a></p></header><main>
<div class="eyebrow">01 / Circulation and dimensions</div><h2>What does the hall give us?</h2><p>The existing hall is a separate route to the living room, snug, guest room, stairs and WC. Its width can be tested. Removing its kitchen wall gives a larger shared space, but the walking route still needs room.</p>
<div class="controls"><label>Plan option<select id="plan"><option value="A">A · Existing hall</option><option value="B">B · Narrower hall</option><option value="C">C · Route through kitchen</option></select></label><label>Pantry arrangement<select id="pantry"><option value="default">Short divider + open passage</option><option value="enclosed">Separate enclosed pantry</option></select></label><label>Kitchen divider<select id="divider"><option value="open">Fully open</option><option value="partial">Partly screened</option><option value="closed">Closed</option></select></label><label>Daylight overlay<select id="light"><option value="off">Off</option><option value="on">Show light connections</option></select></label></div>
<div class="layout"><div class="panel"><svg id="planSvg" viewBox="-1 -1 18.3 18" role="img" aria-label="Measured ground-floor plan with circulation alternatives"></svg><div class="legend"><span class="key"><i style="background:#a45639"></i>Arrival → living</span><span class="key"><i style="background:#47798b"></i>Shopping → pantry</span><span class="key"><i style="background:#c7a767"></i>Oak / glass divider</span><span class="key"><i style="background:#d8ad47"></i>Light connections (when on)</span></div><p class="note">Dimensions in metres. Garden at top; assumed north at bottom. Furniture footprints are schematic. Routes are centre lines, not clearance certification.</p></div><aside class="panel"><div class="metrics" id="metrics"></div><h3 id="optionTitle"></h3><p id="optionText"></p><div class="callout" id="tradeoff"></div><h3>Behind the island stools</h3><p id="clearance"></p><h3>Pantry route</h3><p id="pantryText"></p><p id="routeNote" class="note"></p></aside></div>
<div class="overflow"><table><thead><tr><th>Measured baseline</th><th>Size / area</th><th>What to test</th></tr></thead><tbody><tr><td>Living and dining</td><td>6.20 × 8.95 m / 55.49 m²</td><td>Keep the lounge sheltered and the route outside the furniture group.</td></tr><tr><td>Kitchen</td><td>18.86 m², L-shaped</td><td>Core width 3.90 m; 2.40 × 1.00 m island.</td></tr><tr><td>Hall and entrance</td><td>18.84 m²</td><td>1.55 m cross-hall; 1.80 m entrance leg.</td></tr><tr><td>Pantry + utility</td><td>16.22 m² shared shell</td><td>1.05 m opening past the short divider.</td></tr><tr><td>Separate pantry</td><td>1.65 × 2.10 m / 3.47 m²</td><td>Retain the direct concealed kitchen door.</td></tr></tbody></table></div>
<section class="sections"><div class="eyebrow">02 / Divider study</div><h2>Open, screened or closed.</h2><div class="twocol"><div class="panel"><svg id="dividerSvg" viewBox="0 0 740 580" role="img" aria-label="Kitchen divider elevation"></svg><p id="dividerCaption" class="caption"></p></div><div><p>Test three oak-framed glazed leaves across the existing <strong>2.40 m kitchen opening</strong>. In the open state they stack beside the opening, over the existing 1.30 m wall return.</p><p>The diagram uses a 2.40 m door height with a glazed upper panel to the proposed 3.20 m ceiling. Frame sizes, tracks and support are allowances for this study.</p><p>Between dining and living, test a <strong>1.20 m fixed slat screen at the left-hand wall in the plan</strong>. It is a partial visual boundary, leaving the rest of the 6.20 m room width open. It does not close the lounge.</p><p class="note">Panel overlap will reduce the exact clear width. The stacked panels need depth as well as wall length. Confirm the opening structure, tracks and handles before detailed modelling.</p></div></div></section>
<section class="sections"><div class="eyebrow">03 / Hikari — natural light</div><h2>Let light connect the rooms.</h2><div class="columns"><div><h3>Bright edges</h3><p>The garden bifolds and side windows bring light into living and dining. The kitchen has its own garden-facing window. Keep tall furniture away from these light paths.</p></div><div><h3>Filtered boundaries</h3><p>Clear glazing carries light across the kitchen boundary. Timber slats filter views and cast changing shadows when direct light reaches them. Use the slats in one limited area first.</p></div><div><h3>Quieter inner spaces</h3><p>Warm ivory walls and a pale ceiling can reflect light into the room. Dark oak adds contrast at the island. Keep that darker finish concentrated so the kitchen does not become uniformly dark.</p></div></div><div class="callout"><strong>The overlay shows possible light connections, not sunlight angles or measured illuminance.</strong> The site direction, surrounding obstructions and final window heights are not confirmed. The 3.20 m ceiling is an interior proposal; first-floor levels still need coordination.</div><p>Next light test: compare the selected layout under an overcast sky and low-angle direct light, with the glazed divider open and closed. Keep the camera and exposure fixed. Include curtains and inset shutters so their effect is visible.</p></section>
<section class="sections"><div class="eyebrow">04 / References and next decisions</div><h2>Details that carry into the next model.</h2><div class="twocol"><figure style="margin:0"><img class="image" src="island-reference.png" alt="User reference: dark oak island with framed panels, corner posts and shaped pale countertop"><figcaption class="caption">Selected island direction. Dark oak supersedes the earlier forest green.</figcaption></figure><figure style="margin:0"><img class="image" src="divider-reference.jpeg" alt="User reference: light-filtering timber screens and glazed sliding dividers"><figcaption class="caption">User divider references. Use matching oak tones and simple frames.</figcaption></figure></div><div class="twocol" style="margin-top:24px"><div class="panel"><h3>Tap direction</h3><p>Keep the Belfast-style sink. Test a single lever for flow and temperature, a swivel spout and a pull-out or pull-down rinse for cleaning the bowl.</p><p><a href="https://www.blanco.co.uk/taps/vicus/blancovicus-s_186.615/526689" target="_blank" rel="noopener">BLANCO VICUS-S: pull-out / spray reference ↗</a></p><p><a href="https://media.houseofrohl.design/media/qmwfa4t1/2026_uk_perrin_rowe_kitchen_pricelist.pdf" target="_blank" rel="noopener">Perrin & Rowe Armstrong: pull-down reference ↗</a></p><p class="note">Function references only. Exact shape, finish and compatibility remain open. No asset purchases.</p></div><div class="panel"><h3>My recommendation</h3><p>Compare B and C before choosing. B retains separation and gains about 2.05 m² for the kitchen, but the current stool positions still leave limited space behind them. C gives the greatest freedom to arrange the island and stools, but needs a proper entrance/WC transition and changes the route to the stairs.</p><p>Keep both pantry options. The enclosed version needs a separate decision about a utility-to-pantry door if you want the same direct shopping route.</p><p class="note">Send the new stool reference when ready. No stool design has been selected from the first sheet.</p></div></div></section>
</main><footer><p>Study only. No room boundary, first-floor plan or Blender scene has been changed. Source: studies/l-house-booklet/plans.json; later 5.80 m garden bifolds, closed side garden door and 3.20 m ceiling are shown as proposals from the approved living study. The general daylight approach follows your request and the spatial layering reference at <a href="https://normcph.com/project/kent-avenue-penthouse/">Kent Avenue Penthouse</a>.</p><p><a href="zoning-source.json">Measured source snapshot and calculations</a></p></footer><script>
const data=DATA;
const $=s=>document.querySelector(s);const ns='http://www.w3.org/2000/svg';
function el(parent,tag,attrs={},text){const n=document.createElementNS(ns,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text!==undefined)n.textContent=text;parent.append(n);return n}
function rect(svg,x,y,w,h,fill,stroke='none',sw=.025){return el(svg,'rect',{x,y,width:w,height:h,fill,stroke,'stroke-width':sw})}
function line(svg,x1,y1,x2,y2,stroke,width=.035,dash){return el(svg,'line',{x1,y1,x2,y2,stroke,'stroke-width':width,...(dash?{'stroke-dasharray':dash}:{})})}
function text(svg,x,y,t,size=.22,fill='#334635',anchor='middle'){return el(svg,'text',{x,y,'font-size':size,fill,'text-anchor':anchor,'font-family':'system-ui'},t)}
function path(svg,points,color,width=.07,dash){return el(svg,'polyline',{points:points.map(p=>p.join(',')).join(' '),fill:'none',stroke:color,'stroke-width':width,'stroke-linejoin':'round','stroke-linecap':'round',...(dash?{'stroke-dasharray':dash}:{})})}
const notes={A:['Keep the separate route','The kitchen can close while the hall still serves living, snug, guest room, stairs and WC.','The hall takes 18.84 m². The kitchen remains compact beside a generous living/dining room.'],B:['Give 350 mm back to the kitchen','Move the kitchen/hall partition 350 mm towards the stairs. Keep a 1.20 m cross-hall beside the kitchen; leave the entrance leg and guest-room end of the hall unchanged.','This gains 2.05 m² for the kitchen. The proposed 1.20 m hall width needs a full door, furniture and access check.'],C:['Make the route part of the kitchen','Remove the kitchen/hall partition over its 5.85 m length. Keep the entrance leg and guest-room end of the hall. Approach living through the enlarged kitchen edge.','9.07 m² of hall and 0.88 m² of partition join the shared area. This is not all usable furniture space: retain circulation, and redesign the WC/entrance transition.']};
function draw(){const mode=$('#plan').value,pantry=$('#pantry').value,state=$('#divider').value,light=$('#light').value==='on';const s=$('#planSvg');s.replaceChildren();
 const d=data.plans[pantry], rooms=JSON.parse(JSON.stringify(d.rooms.filter(r=>r.floor==='g'&&r.id!=='L')));let shift=mode==='B'?.35:0;
 const k=rooms.find(r=>r.id==='G2'),h=rooms.find(r=>r.id==='G8');
 if(mode==='B'){k.p=k.p.map(([x,y])=>[x,Math.abs(y-9.3)<.01?y+.35:y]);h.p=[[4.4,9.45],[6.7,9.45],[6.7,9.8],[12.55,9.8],[12.55,14.45],[10.75,14.45],[10.75,11],[4.4,11]]}
 if(mode==='C'){k.p=k.p.map(([x,y])=>[x,Math.abs(y-9.3)<.01?11:y]);h.p=[[4.4,9.45],[6.7,9.45],[6.7,11],[4.4,11]]}
 el(s,'polygon',{points:d.house.map(p=>p.join(',')).join(' '),fill:'#526052'});
 const fills={G1:'#e7dfcb',G2:'#e9dfc5',G3:'#d9e2cf',G4:'#d9e2cf',G8:'#e9e9e1',G10:'#dce3d8'};
 for(const r of rooms)el(s,'polygon',{points:r.p.map(p=>p.join(',')).join(' '),fill:fills[r.id]||'#f6f3eb'});
 if(mode==='C')rect(s,10.75,11,1.8,3.45,'#e9e9e1');
 for(const w of data.windows){if(w.x>16.2)continue;line(s,w.x,w.y,w.x+(w.axis==='h'?w.w:0),w.y+(w.axis==='v'?w.w:0),'#d0edf0',.12)}
 line(s,.55,.175,6.35,.175,'#b1d9dc',.16);text(s,3.45,-.28,'GARDEN · 5.80 m bifolds proposed',.23);
 for(const door of d.doors.filter(o=>o.floor==='g'&&o.x<=16.2)){
 if(mode==='C'&&door.id==='Hall to kitchen')continue;
 let y=door.y+(door.id==='Hall to kitchen'?shift:0);line(s,door.x,y,door.x+(door.axis==='h'?door.w:0),y+(door.axis==='v'?door.w:0),'#fffdf7',.20);
 }
 for(const[f,x,y,axis,w]of d.openings.filter(o=>o[0]==='g'&&o[1]<16.2))line(s,x,y,x+(axis==='h'?w:0),y+(axis==='v'?w:0),'#fffdf7',.32);
 if(mode==='C')line(s,6.625,9.45,6.625,11,'#fffdf7',.18);
 for(const f of d.furniture.filter(f=>f.floor==='g'&&['G2','G3','G4'].includes(f.roomId))){rect(s,...f.r,f.name==='Island'?'#71513d':f.name==='Pantry / utility divider'?'#758769':'#b8bda9','#707b66',.025)}
 // The furniture study supersedes the original dining table size.
 rect(s,1.88,6.055,2.44,1.09,'#bd9d70','#947549');
 for(const f of d.furniture.filter(f=>f.floor==='g'&&f.name==='Dining chair'))rect(s,...f.r,'#ded3bc','#967e5b');
 rect(s,.7,1,4.1,3.2,'#e2d9c6','#9e9a83',.035);text(s,2.75,2.55,'Seating zone',.29);text(s,2.75,2.9,'schematic',.25);
 for(let x=.42;x<1.55;x+=.12)rect(s,x,4.75,.045,.12,'#9c754c');text(s,1.05,5.22,'Screen test',.25);
 const count=state==='open'?0:state==='partial'?1:3;
 line(s,6.625,5.4,6.625,9.1,'#9d8059',.045);
 for(let i=0;i<3;i++){const y=i<count?6.7+i*.8:5.55;line(s,6.61+(i<count?0:i*.065),y,6.61+(i<count?0:i*.065),y+.8,'#ba9a62',.065)}
 if(light){const rays=[[[1, .35],[2.4,3],[4.8,5.6]],[[.35,6.8],[3.6,7],[6.6,7.6],[8.3,7.8]],[[8.6,5.35],[9.3,7],[10.4,9.5]]];for(const p of rays)path(s,p,'#d8ad47',.08,'.14 .12');text(s,10.5,4.7,'Kitchen daylight',.21,'#8c6926');}
 const route=mode==='C'?[[11.78,15.05],[11.78,10.4],[10.65,9.8],[7.12,9.8],[7.12,8.95],[6.15,8.95],[5.45,8.35],[5.45,4.5]]:[[11.78,15.05],[11.78,10.4],[5.45,10.4],[5.45,8.35],[5.45,4.5]];path(s,route,'#a45639');
 const shopping=pantry==='default'?[[15.2,12.4],[15.15,8.9],[14.4,7],[12.05,6.95]]:[[15.2,12.4],[15.15,8.9],[14.4,8.4],[11.1,8.4],[10.35,8.4],[10.35,6.75],[11.7,6.75]];path(s,shopping,'#47798b',.06,'.13 .09');
 const labels=[['Living',3.45,4.4],['Dining',3.1,8.5],['Kitchen',9.35,6.75],['Guest room',2.4,12.1],['Shower',1.2,10.55],['Snug / library',6.2,12.8],['Stairs',9.4,12.8],['Boot room',14.35,13.5],['WC',13.4,10.5],['Arrival',11.8,13.4],['Pantry',11.8,7.18],['Utility',14.35,8.8]];
 for(const[t,x,y]of labels)text(s,x,y,t,t==='Pantry'?.26:.29);
 text(s,8.4,mode==='B'?10.1:10,'1.20 m'+(mode==='B'?' hall':''),.25);
 if(mode!=='B'){const last=s.lastChild;s.removeChild(last);if(mode==='A')text(s,8.4,9.9,'1.55 m hall',.25);else text(s,8.4,10.6,'Shared route',.27)}
 text(s,16.75,12.6,'Link →',.2);line(s,.35,15.7,4.35,15.7,'#334635',.06);for(let i=0;i<=4;i++){line(s,.35+i,15.6,.35+i,15.8,'#334635',.03);text(s,.35+i,16.1,String(i),.19)}text(s,4.7,16.1,'m',.19);line(s,15.2,15.2,15.2,16,'#334635',.04);path(s,[[15,15.75],[15.2,16],[15.4,15.75]],'#334635',.04);text(s,15.2,16.45,'N assumed',.25);
 const m=data.metrics,kArea=m.kitchen+(mode==='B'?m.narrow_gain:mode==='C'?m.open_hall_reassigned+m.open_partition_recovered:0),hArea=m.hall-(mode==='B'?m.narrow_gain:mode==='C'?m.open_hall_reassigned:0);
 $('#metrics').innerHTML=`<div class="metric"><b>${(Math.round((kArea+1e-9)*100)/100).toFixed(2)} m²</b><span>${mode==='C'?'Kitchen + shared route':'Kitchen'}</span></div><div class="metric"><b>${(Math.round((hArea+1e-9)*100)/100).toFixed(2)} m²</b><span>Separate hall / entrance</span></div>`;
 $('#optionTitle').textContent=notes[mode][0];$('#optionText').textContent=notes[mode][1];$('#tradeoff').textContent=notes[mode][2];
 $('#clearance').textContent=mode==='A'?'The source stool footprints leave 0.50 m to the rear kitchen wall. That is not a convincing through-route once someone is seated.':mode==='B'?'Moving the wall adds 0.35 m, giving 0.85 m behind the source stool footprints. This improves the gap, but the new stools and seated use still need testing.':'The partition is removed, so the old 0.50 m gap is no longer bounded by a wall. The route crosses the shared kitchen edge; keep it outside the prep aisle and the occupied stool space.';
 $('#pantryText').textContent=pantry==='default'?'The 1.05 m opening lets shopping pass from boot room through utility into the pantry. The direct kitchen pantry door remains.':'The enclosed pantry is 3.47 m². The preserved option has no utility-to-pantry door: shopping passes through the kitchen. A connecting door would be a new option.';
 $('#routeNote').textContent=mode==='C'&&state==='closed'?'The living route crosses the closed kitchen divider. A leaf must open to pass; this is not an independent bypass.':'The red and blue lines show route intent. Door swings, occupied chairs and accessibility still need a detailed check.';
 divider(state);
}
function divider(state){const s=$('#dividerSvg');s.replaceChildren();rect(s,0,0,740,580,'#f1ecdf');rect(s,35,45,190,467,'#e0dacd');rect(s,225,45,350,467,'#e8eee4');text(s,130,548,'1.30 m return',14);text(s,400,548,'2.40 m opening',14);text(s,660,265,'3.20 m',14);text(s,660,286,'ceiling test',12);line(s,225,512,575,512,'#6e745e',2);rect(s,225,45,350,117,'#d0e0d9','#a8895c',5);text(s,400,112,'Glazed upper panel',14);line(s,55,162,575,162,'#957346',5);
 const n=state==='open'?0:state==='partial'?1:3;for(let i=0;i<3;i++){let x=i<n?225+i*116.7:80+(i-n)*10;rect(s,x,168,116.7,344,'#c7e0db88','#aa8553',6);line(s,x+5,411,x+110,411,'#aa8553',3)}
 $('#dividerCaption').textContent={open:'Fully open: leaves stack over the wall return. Nominal opening 2.40 m before frame and hardware allowances.',partial:'Partly screened: one leaf spans part of the opening. This adds a visual boundary while leaving a passage.',closed:'Closed: all three glazed leaves span the opening. Light and views remain; acoustic performance depends on the complete door system.'}[state];}
 document.querySelectorAll('select').forEach(x=>x.addEventListener('change',draw));draw();
</script></body></html>'''.replace('DATA',json.dumps(data,separators=(',',':')))
(O/'zoning.html').write_text(page)
print(json.dumps(metrics,indent=2));print(O/'zoning.html')
