const assert=require('node:assert/strict');
const path=require('node:path');
const fs=require('node:fs');
const baseURL=process.env.BASE_URL||'http://127.0.0.1:4186/';
const localChrome='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const root=path.resolve(__dirname,'..');
const {chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||(fs.existsSync(localChrome)?localChrome:undefined),headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 fs.mkdirSync(path.join(root,'tmp/pdfs'),{recursive:true});
 try { const page=await browser.newPage({viewport:process.env.CI?{width:900,height:640}:{width:1400,height:1000}});page.setDefaultTimeout(30000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',route=>route.request().url().startsWith(baseURL)?route.continue():route.abort());
 await page.goto(new URL('viewer/',baseURL).href);await page.waitForFunction(()=>window.house);
 assert.equal(await page.evaluate(()=>house.model.rooms.length),26);
 const physical=await page.evaluate(async()=>{
  const THREE=await import(new URL('viewer/vendor/three.module.js',location.origin+location.pathname.split('viewer/')[0]).href);
  house.scene.updateMatrixWorld(true);
  const ray=new THREE.Raycaster();
  const openings=house.model.rooflights.map(light=>{
   const [x,z,w,d]=light.rect;ray.set(new THREE.Vector3(x+w/2,1,z+d/2),new THREE.Vector3(0,1,0));
   const hits=ray.intersectObjects(house.scene.children,true).filter(h=>h.object.isMesh&&h.point.y>2.5);
   return hits.length>0&&hits.every(h=>h.object.material.transparent);
  });
  const chairBacks=[];
  house.scene.traverse(o=>{
   if(!['Dining north','Dining south'].includes(o.userData.name))return;
   let back;o.traverse(c=>{if(c.name==='Chair back')back=c;});
   const north=o.userData.name==='Dining north';
   chairBacks.push(back&&Math.abs(new THREE.Box3().setFromObject(back).getCenter(new THREE.Vector3()).z-(north?5.635:7.765))<.01);
  });
  const mappedSurfaces=[],roofNormals=[],roofNames=new Set(house.model.roofSurfaces.map(r=>r.name));
  house.scene.traverse(o=>{
   if(!o.isMesh)return;
   if(roofNames.has(o.name)){const normals=o.geometry.getAttribute('normal');roofNormals.push(Array.from({length:normals.count},(_,i)=>normals.getY(i)>.5).every(Boolean));}
   const materials=Array.isArray(o.material)?o.material:[o.material];
   if(!materials.some(m=>m.map))return;
   const uv=o.geometry.getAttribute('uv');mappedSurfaces.push(Boolean(uv)&&Array.from(uv.array).every(Number.isFinite));
  });
  const wallSamples=[];
  for(const wall of house.model.walls.filter(w=>w.material==='stone'&&w.rect[1]===0&&w.bottom===0)){
   ray.set(new THREE.Vector3(wall.rect[0]+wall.rect[2]/2,Math.min(1,wall.top/2),-1),new THREE.Vector3(0,0,1));
   const hit=ray.intersectObjects(house.scene.children,true).find(h=>h.object.isMesh&&h.point.z<.01);
   if(hit?.uv)wallSamples.push([hit.point.x,hit.uv.x]);
  }
  return {openings,chairBacks,mappedSurfaces,wallSamples,roofNormals};
 });
 assert(physical.roofNormals.length>6&&physical.roofNormals.every(Boolean),'Roof normals point inward and produce self-shadow artefacts');
 assert(physical.mappedSurfaces.length>100&&physical.mappedSurfaces.every(Boolean),'Textured surface has missing or invalid UV coordinates');
 assert(physical.wallSamples.length>1,'Missing wall samples');
 const [firstX,firstU]=physical.wallSamples[0];
 for(const [x,u] of physical.wallSamples)assert(Math.abs((u-firstU)-(x-firstX)/2.4)<.001,'Stone courses change scale or alignment across wall pieces');
 assert.equal(physical.openings.length,6);assert(physical.openings.every(Boolean),'Rooflight blocked by opaque roof or ceiling');
 assert.equal(physical.chairBacks.length,8);assert(physical.chairBacks.every(Boolean),'Outdoor dining chair faces away from table');
 const book=await page.request.get(new URL('output/pdf/house-design-book.pdf',baseURL).href);assert.equal(book.status(),200);assert.equal((await book.body()).subarray(0,4).toString(),'%PDF');

 await page.getByRole('button',{name:'Plan',exact:true}).click();assert.equal(await page.evaluate(()=>house.state.roofOn),false);
 await page.getByRole('button',{name:'Office',exact:true}).click();
 await page.getByLabel('Office use').selectOption('Night');
 let furniture=await page.evaluate(()=>house.state.officeFurniture);assert(furniture.some(n=>n.toLowerCase().includes('open')));assert(furniture.includes('Professional workspace'));assert(furniture.includes('Personal workspace'));assert(!furniture.includes('Sofa bed closed'));
 await page.getByLabel('Office use').selectOption('Personal');assert((await page.evaluate(()=>house.state.officeFurniture)).includes('Sofa bed closed'));
 await page.getByRole('button',{name:'Daylight',exact:true}).click();assert.equal(await page.evaluate(()=>house.state.night),true);
 await page.getByRole('button',{name:'Evening',exact:true}).click();
 await page.getByRole('button',{name:'Shared room',exact:true}).click();
 await page.getByRole('button',{name:'Walk',exact:true}).click();const before=await page.evaluate(()=>house.camera.position.toArray());
 await page.keyboard.down('w');await page.waitForFunction(before=>house.camera.position.distanceTo({x:before[0],y:before[1],z:before[2]})>.05,before,{timeout:15000});await page.keyboard.up('w');const after=await page.evaluate(()=>house.camera.position.toArray());assert.notDeepEqual(before,after);
 const pose=()=>page.evaluate(()=>({position:house.camera.position.toArray(),direction:house.camera.getWorldDirection(house.camera.position.clone()).toArray()}));
 const turnedFrom=await pose();await page.keyboard.down('ArrowLeft');
 await page.waitForFunction(before=>house.camera.getWorldDirection(house.camera.position.clone()).distanceTo({x:before[0],y:before[1],z:before[2]})>.15,turnedFrom.direction);await page.keyboard.up('ArrowLeft');
 const turnedLeft=await pose();assert(turnedLeft.direction[0]*-turnedFrom.direction[2]+turnedLeft.direction[2]*turnedFrom.direction[0]<0,'Left arrow must turn left');assert.deepEqual(turnedLeft.position,turnedFrom.position,'Turning must not move sideways');
 await page.keyboard.down('ArrowRight');await page.waitForFunction(before=>house.camera.getWorldDirection(house.camera.position.clone()).distanceTo({x:before[0],y:before[1],z:before[2]})>.15,turnedLeft.direction);await page.keyboard.up('ArrowRight');
 const turnedRight=await pose();assert(turnedRight.direction[0]*-turnedLeft.direction[2]+turnedRight.direction[2]*turnedLeft.direction[0]>0,'Right arrow must turn right');assert.deepEqual(turnedRight.position,turnedFrom.position);
 await page.evaluate(()=>{house.camera.position.set(17.8,1.65,17.4);house.camera.lookAt(13.8,1.65,17.4);});
 const combined=await pose();await page.keyboard.down('ArrowUp');await page.keyboard.down('ArrowLeft');
 await page.waitForFunction(before=>house.camera.position.distanceTo({x:before.position[0],y:before.position[1],z:before.position[2]})>.1&&house.camera.getWorldDirection(house.camera.position.clone()).distanceTo({x:before.direction[0],y:before.direction[1],z:before.direction[2]})>.1,combined);
 await page.keyboard.up('ArrowUp');await page.keyboard.up('ArrowLeft');
 const reversed=await pose();await page.keyboard.down('ArrowDown');await page.waitForFunction(before=>house.camera.position.distanceTo({x:before[0],y:before[1],z:before[2]})>.1,reversed.position);await page.keyboard.up('ArrowDown');
 const strafe=await pose();await page.keyboard.down('Shift');await page.keyboard.down('d');await page.waitForFunction(before=>house.camera.position.distanceTo({x:before[0],y:before[1],z:before[2]})>.1,strafe.position);await page.keyboard.up('d');await page.keyboard.up('Shift');assert.deepEqual((await pose()).direction,strafe.direction);
 const dragFrom=await pose();await page.mouse.move(700,400);await page.mouse.down();await page.mouse.move(760,430);await page.mouse.up();assert.notDeepEqual((await pose()).direction,dragFrom.direction);
 await page.evaluate(()=>document.querySelector('#roof-toggle').focus());const focused=await pose();await page.keyboard.press('ArrowUp');assert.deepEqual(await pose(),focused,'UI focus must not move the camera');
 await page.evaluate(()=>{house.renderer.domElement.focus();house.camera.position.set(17.8,1.65,17.4);house.camera.lookAt(17.8,1.65,13.4);});
 await page.getByRole('button',{name:'Mouse look',exact:true}).click();
 await page.waitForFunction(()=>document.pointerLockElement===house.renderer.domElement);
 const locked=await pose();await page.mouse.move(600,300);await page.mouse.move(650,330);assert.notDeepEqual((await pose()).direction,locked.direction,'Locked mouse must turn without dragging');
 await page.keyboard.press('Escape');await page.waitForFunction(()=>!house.state.walking&&document.pointerLockElement===null);
 await page.getByRole('button',{name:'Walk',exact:true}).click();await page.getByRole('button',{name:'Mouse look',exact:true}).click();await page.waitForFunction(()=>document.pointerLockElement===house.renderer.domElement);
 await page.evaluate(()=>document.exitPointerLock());await page.waitForFunction(()=>!house.state.walking);
 assert.equal(await page.evaluate(()=>document.pointerLockElement),null);assert.equal(await page.locator('#walk-controls').isVisible(),false);
 await page.getByRole('button',{name:'Walk',exact:true}).click();
 await page.evaluate(()=>{house.renderer.domElement.requestPointerLock=()=>Promise.reject(new Error('Unavailable'));});
 await page.getByRole('button',{name:'Mouse look',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#view-note').textContent.startsWith('Mouse look is unavailable.'));
 assert.equal(await page.evaluate(()=>house.state.walking),true);await page.evaluate(()=>delete house.renderer.domElement.requestPointerLock);
 assert.equal(await page.evaluate(()=>house.canMove(.175,5)),false);assert.equal(await page.evaluate(()=>house.canMove(17.8,17.4)),true);
 await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>house.state.walking),false);
 await page.evaluate(()=>{house.camera.position.set(18.1,1.65,20.5);house.setWalking(true);house.camera.position.set(18.1,1.65,20.5);house.camera.lookAt(18.1,1.1,18.225);});
 await page.evaluate(()=>house.renderer.render(house.scene,house.camera));const viewport=page.viewportSize();await page.mouse.click(viewport.width/2,viewport.height/2);
 assert.equal(await page.evaluate(()=>{let open;house.scene.traverse(o=>{if(o.userData.door?.data.id==='D15')open=o.userData.door.open;});return open;}),true);
 const doorOpen=()=>page.evaluate(()=>{let open;house.scene.traverse(o=>{if(o.userData.door?.data.id==='D15')open=o.userData.door.open;});return open;});
 await page.waitForFunction(()=>document.querySelector('#door-hint').textContent==='Space — Close door');
 await page.waitForFunction(()=>{let settled=true;house.scene.traverse(o=>{const door=o.userData.door;if(door&&Math.abs(Number(door.open)-door.progress)>.001)settled=false;});return settled;});
 await page.screenshot({path:path.join(root,'tmp/pdfs/walkthrough-door.png'),timeout:60000});
 await page.keyboard.down('Space');assert.equal(await doorOpen(),false);await page.keyboard.down('Space');assert.equal(await doorOpen(),false,'Holding Space must not toggle repeatedly');await page.keyboard.up('Space');
 await page.waitForFunction(()=>document.querySelector('#door-hint').textContent==='Space — Open door');
 await page.keyboard.press('Space');assert.equal(await doorOpen(),true);
 await page.evaluate(()=>house.camera.lookAt(18.1,1.65,24));await page.waitForFunction(()=>document.querySelector('#door-hint').hidden);await page.keyboard.press('Space');assert.equal(await doorOpen(),true,'Looking away must not operate the door');
 await page.evaluate(()=>{house.camera.position.set(18.1,1.65,23);house.camera.lookAt(18.1,1.1,18.225);});await page.keyboard.press('Space');assert.equal(await doorOpen(),true,'Distant door must not operate');
 await page.keyboard.press('Escape');const stopped=await pose();await page.keyboard.press('ArrowUp');await page.keyboard.press('Space');const inactive=await pose();assert(inactive.position.every((v,i)=>Math.abs(v-stopped.position[i])<1e-6)&&inactive.direction.every((v,i)=>Math.abs(v-stopped.direction[i])<1e-6),'Movement keys must be inactive after Escape');
 await page.getByRole('button',{name:'Whole house',exact:true}).click();
 await page.screenshot({path:path.join(root,'tmp/pdfs/viewer-desktop.png'),timeout:60000});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(root,'tmp/pdfs/viewer-mobile.png'),timeout:60000});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false);
 await page.getByRole('button',{name:'Shared room',exact:true}).click();await page.getByRole('button',{name:'Walk',exact:true}).click();
 await page.screenshot({path:path.join(root,'tmp/pdfs/walkthrough-mobile.png'),timeout:60000});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 assert.deepEqual(errors,[]);console.log('Passed texture mapping and stone scale, rooflight rays, outdoor chair orientation, PDF download, local-only load, view controls, office states, day/evening, walking, arrow turning, combined movement, drag and locked mouse look, focus handling, Space door interaction, wall collision and mobile overflow checks');
 } finally { await browser.close(); }
})();
